### ISSUE TITLE
Output is zero

### ISSUE THREAD

**Issue by solomonsg** [c-h-david/rapid#18]
Hi Cédric,

after running rapid, I am getting almost all values close to zore (0.000005) even at catchment outlet.  it is even much lower than the input runoff (m3). i did try using netcdf3 and netcdf4 but it did not help. 
the input file has 13880 days, daily runoff. 
          

>  !*******************************************************************************
>           !Temporal information
>            !*******************************************************************************
>           ZS_TauM         =1199232000
>          !3600*24*13880=1199232000

> ZS_dtM	        =86400

> !3600*24=86400

> ZS_TauO         =0

> !3600*24*0=0
> ZS_dtO          =0
> !3600*24*0=0
> 
> ZS_TauR		=86400
> !3600*24=86400
> ZS_dtR		=1800 
> !60*30=1800
> 
> ZS_dtF          =86400          
> !3600*24=86400

please can you help?

**Comment by c-h-david** [comment]
Hi Solomon,
The values in your `namelist` are in line with your experiment design: daily timestep of runoff: `ZS_TauR=86400`, daily loops `ZS_dtM=86400` (the need for this variable in the RAPID code design can probably be debated, but is used properly here), and total experiment duration `ZS_TauM =1199232000`. If you're getting near-zero outputs, it might be that the units in your `m3_riv` file are not cubic meters from daily accumulation of runoff. I'd double check that if I were you, but the issue could be coming from elsewhere. Not sure!
Cedric
