### ISSUE TITLE
Muskingum parameters not converging

### ISSUE THREAD

**Issue by elyssac02** [c-h-david/rapid#24]
Hi,

I hope you're doing well. I have been trying to run RAPID in optimization mode to identify the optimal values for lambda k, lambda x, and phi. However, when I use the `tst_opt_find.sh` script (found [here](https://github.com/c-h-david/rapid/blob/master/tst/tst_opt_find.sh)) to extract the appropriate values from the optimization text file, I receive the following output:

```bash
Best results - RAPID optimization converged to meaningless values after 51 function evaluations, last valid set was evaluation 20
```

What typically causes the failure to converge to meaningful values? Just trying to figure out generally where I should be looking/what I should be modifying in order to get the parameters to converge.

Thanks,

Elyssa

**Comment by c-h-david** [comment]
Hi Elyssa,
The optimization method that RAPID uses is "unconstrained", meaning it will produce parameters that minimize the cost function regardless of whether or not they make physical sense (_i.e._ k>0 and x within [0;0.5]). However, the `tst_opt_find.sh` script that is included allows to determine the parameter values that lead to the smallest cost function while still making physical sense. These are the parameters you should use. 
Inaccurate/imperfect runoff is often the culprit in cases of physically-meaningless optimization results.
You might fight some valuable information on the optimization methods in RAPID in https://doi.org/10.1016/j.envsoft.2012.12.011 and  https://doi.org/10.1002/hyp.8070.
I hope this helps!  
Best,
Cedric
