### ISSUE TITLE
[question]: Optimization - when to run in broader calibration process

### ISSUE THREAD

**Issue by KMarkert** [c-h-david/rapid#29]
### What would you like to ask?

I am working on a project focusing on setting up a LSM with routing for future climate projections using VIC and RAPID. 

Part of the project involves calibrating VIC. While calibrating VIC does a reasonable job at generating historically observed streamflow, I am wondering on how optimizing the RAPID parameters fits within a calibration process. For example, a calibration loop will include updating the LSM parameters, then run LSM and finally run routing for streamflow. When considering incorporating RAPID optimization for calibration which order of operations would be considered best practice:

1.  update LSM parameters -> run LSM model -> optimize RAPID -> run RAPID - evaluate loop
2.  update LSM parameters -> run LSM model -> run RAPID - evaluate loop -> optimize RAPID with calibrated LSM

Both options seems valid from my perspective. The RAPID optimization would depend on the calibrated runoff from the LSM so would running RAPID optimization for each loop be overkill?

Thanks in advance for your insight!

### Let us ensure open source development is sustainable!

- [X] I have looked at previous GitHub issues and this question has not yet been addressed.

- [X] I have already submitted one unique GitHub issue with my RAPID User Information.

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142).

**Comment by c-h-david** [comment]
Hi Kel, this is such a good question, and a can of worms... you might want to take a look at: http://dx.doi.org/10.1016/j.envsoft.2012.12.011. My recommendation is that you decouple the calibrations of VIC and that of RAPID as much as possible. Pick some RAPID `k` and `x` parameters that generally make sense, and optimize VIC, perhaps including the execution of RAPID (but not the optimization of RAPID) in that loop. Only optimize RAPID at the end once you're satisified with your runoff. The success of the RAPID optimization depends heavily on the quality of the runoff. So best to provide good runoff first, before optimizing RAPID. Hope this helps!

Also, when you get a chance, could you fill a `RAPID User Information` form at https://github.com/c-h-david/rapid/issues/new/choose? I know you're a long-time user, but this is a new feature to capture everyone using it!

**Comment by KMarkert** [comment]
Thanks for the guidance on such a loaded topic, Cedric!

I will read through the paper shared. Most examples of RAPID I have seen in literature use the approach you mentioned which is the approach I was leaning towards but I have seen other routing models, such as [RVIC](https://agupubs.onlinelibrary.wiley.com/doi/10.1002/2016JC012323), be calibrated within the same loop as the LSM, so I was second guessing things. 

Thanks again for clarification!

Also, I filled out the RAPID User Information.

**Comment by martaddi** [comment]
> 

Hi,
could you help me the the calibration of VIC and RAPID? I quit new to this. Any help will be appreciated.
Thanks.
