### ISSUE TITLE
[user]: Jim Nelson

### ISSUE THREAD

**Issue by geosjim** [c-h-david/rapid#30]
### Your Name

Jim Nelson

### Your Institution

BYU (GEOGloWS)

### Your Location

Provo, Utah

### Your Use Case

Routing the ensemble global ECMWF gridded runoff through a globally delineated river network to provide forecast as a service on nearly 1,000,000 river reaches worldwide.
https://geoglows.ecmwf.int/
https://apps.geoglows.org/apps/geoglows-hydroviewer/

### Why RAPID?

It provides fast (dare we say rapid) calculations that transform gridded runoff to discharge hydrographs at points. It has been robust and easy to incorporate into the workflow that produces historical simulations from the ERA-5 retrospective analysis data and daily 15-day ensemble forecasts.

### How do you use RAPID?

We have done both self installation, and now docker images (though to be honest I believe that we dockerized our instance of RAPID prior to the availability of the docker images and I'm not sure if we have switched?

### Anything else you'd like us to know?

This tool was just the right thing for helping us to develop a global hydrologic modeling service, we would have gotten nowhere without it.

### Are you aware of our philosphy for open source?

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142) (the one starting with
 "Finally, and contrary to common belief, open source software does
not mean...")

**Comment by c-h-david** [comment]
@geosjim, thank you for submitting your `RAPID User Information` form! But more importantly, thank you for our many years of successful collaborations and for your advocacy of the RAPID model!
