### ISSUE TITLE
[user]: Kel Markert

### ISSUE THREAD

**Issue by KMarkert** [c-h-david/rapid#31]
### Your Name

Kel Markert

### Your Institution

Brigham Young University

### Your Location

Huntsville, AL

### Your Use Case

Working on project to simulate historical (1980-present) and future (present - 2100) water resources in the state of Utah using the [VIC](https://github.com/uw-hydro/vic) model as the land surface component and RAPID for streamflow routing. Modeling is focusing on understanding changes in streamflow, snow pack, and reservoir storage with changing climate.

### Why RAPID?

RAPID is open source and provides streamflow within every reach of a stream network.

### How do you use RAPID?

Using own docker image that has the different model components installed. Testing setup locally, running on HPC cluster and GCP.

### Are you aware of our philosphy for open source?

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142) (the one starting with
 "Finally, and contrary to common belief, open source software does
not mean...")

**Comment by c-h-david** [comment]
@KMarkert thank you for submitting your `RAPID User Information` form!
