### ISSUE TITLE
[question]: How Rapid can be used for parallel computing on Linux? At present, it takes too long.

### ISSUE THREAD

**Issue by hhrhrhehxcshdfsrg** [c-h-david/rapid#32]
### What would you like to ask?

How Rapid can be used for parallel computing on Linux? At present, it takes too long.

### Let us ensure open source development is sustainable!

- [X] I have looked at previous GitHub issues and this question has not yet been addressed.

- [X] I have already submitted one unique GitHub issue with my RAPID User Information.

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142).

**Comment by c-h-david** [comment]
Dear @hhrhrhehxcshdfsrg, thank you for your interest in RAPID! I see you indicated above that you had already completed the `RAPID User Information` form, but I can't find it!  Did I miss it?  Can you please point me to it?  Thanks so much for your help keeping open source development sustainable. 
Best regards,
Cedric
