### ISSUE TITLE
[user]: Hao Haoran

### ISSUE THREAD

**Issue by hhrhrhehxcshdfsrg** [c-h-david/rapid#33]
### Your Name

Hao haoran

### Your Institution

Tianjin University

### Your Location

Tianjin China

### Your Use Case

I intend to use MERIT data to complete accurate river discharge simulation in China using RAPID based on runoff data from land surface hydrological model.

### Why RAPID?

The RAPID model was recommended to me by my senior brother. After I got in touch with it, I found that the model can realize parallel computing, and it is easy to accept, and it is widely used. However, some problems are still unclear.

### How do you use RAPID?

I did the installation myself and it is currently running on a high performance computer.

### Anything else you'd like us to know?

I hope to learn the model well and realize the simulation effect.

### Are you aware of our philosphy for open source?

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142) (the one starting with
 "Finally, and contrary to common belief, open source software does
not mean...")

**Comment by c-h-david** [comment]
Dear Hao Haoran,
Welcome to the community of RAPID users!  Thank you for submitting your user information form.
Best,
Cedric
