### ISSUE TITLE
[question]: Executing RAPID in parallel

### ISSUE THREAD

**Issue by hhrhrhehxcshdfsrg** [c-h-david/rapid#34]
### What would you like to ask?

Hi, I have successfully run the RAPID model, which takes about 40 minutes for a time period of 200,000 rivers. I want to know how to set the parallel computing. Do I need to set it in Namelist?

### Let us ensure open source development is sustainable!

- [X] I have looked at previous GitHub issues and this question has not yet been addressed.

- [X] I have already submitted one unique GitHub issue with my RAPID User Information.

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142).

**Comment by c-h-david** [comment]
Hi Hao Haoran, 
I usually run RAPID in parallel with `mpiexec -n 4 ./rapid` (example using 4 cores). For faster performance, you might want to make sure that your `riv_bas_id_file` is sorted from upstream to downstream.  
If your river reaches are sorted from upstream to downstream you should also be able to run on 1 core with `mpiexec -n 1 ./rapid -ksp_type=preonly`.  Be careful **not** to use this last example with multiple cores, this wouldn't give accurate results.
Best,
Cedric
