### ISSUE TITLE
[question]: Grid size issue with runoff

### ISSUE THREAD

**Issue by hhrhrhehxcshdfsrg** [c-h-david/rapid#35]
### What would you like to ask?

The runoff data grid size used in my model is 5km for computational power reasons. I use MERIT data to build a rapid model. I know that the finer the grid size, the better the simulation may be. But I would like to ask whether the coarse grid resolution has a great influence on the calculation results? Have you done any research on this?

### Let us ensure open source development is sustainable!

- [X] I have looked at previous GitHub issues and this question has not yet been addressed.

- [X] I have already submitted one unique GitHub issue with my RAPID User Information.

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142).

**Comment by c-h-david** [comment]
@hhrhrhehxcshdfsrg, I haven't personally dedicated much effort to the influence of the spatial resolution of the runoff dataset on the quality of discharge computations. I usually just make sure that the runoff grid is coarser than the catchment sizes, and then apply a simple centroid-based transformation (see https://doi.org/10.1016/j.envsoft.2012.12.011). There are also other transformation options (for example: https://doi.org/10.1016/j.envsoft.2018.05.018). But I agree that evaluating the impact of the runoff resolution would be an interesting endeavor.
