### ISSUE TITLE
[user]: Mike Follum

### ISSUE THREAD

**Issue by MikeFHS** [c-h-david/rapid#36]
### Your Name

Mike Follum

### Your Institution

Private Company - Follum Hydrologic Solutions, LLC

### Your Location

Casper, WY

### Your Use Case

I use streamflow data from RAPID to drive large-scale flood inundation mapping both within the United States (NHDPlus) and outside the continental United States (OCONUS).  When I'm working with the U.S. Army Coastal and Hydraulics Laboratory (CHL) the RAPID model is part of their Streamflow Prediction Tool (using ECMWS 2-week runoff forecast data).  When I'm working with Brigham Young University the RAPID model is part of the GEOGLoWs system.

It's been improved upon multiple times, but the following links describes connecting RAPID to flood mapping capabilities:  https://doi.org/10.1111/1752-1688.12476;  https://doi.org/10.5194/nhess-20-625-2020

### Why RAPID?

RAPID is used because it can be set-up relatively quickly for a basin and simulates the flow rates fairly well.

### How do you use RAPID?

I rely on the U.S. Army Coastal and Hydraulics Laboratory (CHL) and ECMWS/BYU to simulate RAPID.

### Anything else you'd like us to know?

RAPID has helped change how flood forecasting is conducted both within the U.S. and OCONUS.  More advanced systems may come in the future, but for now RAPID has shown to be functional both in the literature as well as in operations.

### Are you aware of our philosphy for open source?

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142) (the one starting with
 "Finally, and contrary to common belief, open source software does
not mean...")

**Comment by c-h-david** [comment]
@MikeFHS, thank you for submitting your `RAPID User Information` form!
