### ISSUE TITLE
[user]: Riley Hales

### ISSUE THREAD

**Issue by rileyhales** [c-h-david/rapid#37]
### Your Name

Riley Hales

### Your Institution

Brigham Young University

### Your Location

Provo Utah USA

### Your Use Case

I (speaking on behalf of my colleagues) use RAPID as a component of a global hydrologic modeling program sponsored by the GEOGloWS (Group on Earth Observations Global Water Sustainability) Initiative. This started as a research idea for the National Water Center which was a precursor to what is now the National Water Model. This model is currently scaling up to cover almost the full world, 9-10 million basins, ECMWF forecast & hindcast runoff, a brand new delineated stream network created by the NGA (national geospatial intelligence agency) derived from the TanDEMX 10 meter DEM.

### Why RAPID?

Some of the important features of rapid for my applications are:
- calculates on vector basins rather than grids
- No GUI -> easily controlled with command line scripts which is important for automation.
- implements a sufficiently sophisticated routing method to get good results
- scales well computationally speaking (though I only barely learned from you the way i was taught to use rapid was not remotely the most efficient way!)
- open source

### How do you use RAPID?

I compile rapid directly on an ECMWF supercomputer and then use rapidpy (https://github.com/byu-hydroinformatics/rapidpy) to orchestrate running the many simulations (per watershed, forecast and hindcast, etc) in parallel as new forecast/hindcast runoff data is available. I am transitioning away from that approach and will likely take more advantage of the docker images and compute clusters on their infrastructure. We test and perform other simulations on standard desktops/laptops and on AWS and Azure.

### Anything else you'd like us to know?

As we've recently discovered, the BYU/GEOGloWS crowd haven't been using rapid as efficiently as possible. We'd like to find a way to help compile some additional documentation/cheat-sheets for the rapid_namelist file, the options for solvers, and a few things like that to better help us be self sufficient. We can generate that but would need it to be checked by someone who knows.

### Are you aware of our philosphy for open source?

- [X] I have read the last paragraph of Section 6.3 in [David et al., 2016](https://doi.org/10.1002/2015EA000142) (the one starting with
 "Finally, and contrary to common belief, open source software does
not mean...")

**Comment by c-h-david** [comment]
@rileyhales, thanks for completing your `RAPID User Information` form! Listen, I love the idea of community crowd-sourced information to help RAPID users. I've actually been contemplating trying to update the [RAPID website](http://rapid-hub.org) to instead use the markdown language and publish the website code on GitHub for easy updates . If you'd like to draft a short (say one-page) document that explains what you recently learnt, I'll find a way to include it! Happy to chat about this as well.
