### ISSUE TITLE
Has the namelist changed?

### ISSUE THREAD

**Issue by msomos** [c-h-david/rapid#5]
Hi Ced
This is not really an issue, anyway here it goes. Last time I used rapid I worked with a 2015 version but now I can see that the ouptuts have changed including lat lon for example, is there an example on how to set the files to run RAPID with the latest update? I could not figure it out checking your website
Thanks
M

**Comment by c-h-david** [comment]
Hi Marcelo,
You'll find a document summarizing how RAPID was adapted to adopt the netCDF Climate and Forecast (CF) conventions in the Documents section of the RAPID website (http://rapid-hub.org/documents.html).  
Note, however, that your old RAPID files should still be compatible with the latest versions of the source code. I don't believe that the namelist has changed as a consequence of CF conventions usage.  RAPID looks for "lon", "lat", and "time" values (among other things) directly in the input file that has the runoff and passes the information along to the output files.
I don't yet have example runoff files online, but the Reproducible Routing Rituals (RRR, https://github.com/c-h-david/rrr) allows to make those.
I hope this helps!
Cedric

**Comment by msomos** [comment]
Now it all makes sense, 
Thanks a lot,
Marcelo

**Comment by c-h-david** [comment]
No worries.  Issue closed then.  Thanks for being a RAPID user!
Cedric
